---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: false

platforms:
- name: cap-base
  driver_config:
    box: cap-base-centos-6.4
    box_url: ~/.vagrant-boxes/cap-base-centos-6.4-v0.1.0.box

suites:
- name: default
  run_list: ["recipe[heirloom-cookbook]"]
  attributes: {}
